version: 0.2

phases:
  install:
    commands:
      - echo "Installing NGINX..."
      - yum install -y nginx
      - echo "NGINX installed successfully."

  build:
    commands:
      - echo "Build started on `date`"
      - mkdir -p /usr/share/nginx/html/assets
      - cp index.html /usr/share/nginx/html/index.html
      - cp -r assets/* /usr/share/nginx/html/assets/
      - echo "Static files copied to /usr/share/nginx/html/"
      - echo "Build completed on `date`"

  post_build:
    commands:
      - echo "Testing NGINX configuration..."
      - nginx -t
      - echo "NGINX configuration is valid."
      - echo "Contents of /usr/share/nginx/html:"
      - ls -R /usr/share/nginx/html

artifacts:
  files:
    - '**/*'
  base-directory: /usr/share/nginx/html
